/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ct.csv2pdf;

import com.opencsv.exceptions.CsvValidationException;
import java.awt.CardLayout;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.TransferHandler;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

   
/**
 *
 * @author Cem
 */
public class GUI extends JFrame {

    private CSV2PDF service;
    CSV2PDF.PDFConfig config;
    private List<String[]> data;
    private String path;
    private DefaultTableModel tableModel = new DefaultTableModel();

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        
        DefaultComboBoxModel<ComboItem> model = new DefaultComboBoxModel<>();
        model.addElement(new ComboItem("Komma ( , )", ","));
        model.addElement(new ComboItem("Semicolon ( ; )", ";"));
        model.addElement(new ComboItem("Tab", "\t"));
        model.addElement(new ComboItem("Space", " "));
        jComboBoxDelimeter.setModel(model);
       
        jComboBoxFontName.removeAllItems();
        jComboBoxFontName.addItem("Helvetica");
        jComboBoxFontName.addItem("Helvetica Bold");
        jComboBoxFontName.addItem("Times Roman");
        jComboBoxFontName.addItem("Courier");
        jComboBoxFontName.addItem("Courier Bold");  
        
    ((JComponent) getContentPane()).setTransferHandler(new TransferHandler() {
        @Override
        public boolean canImport(TransferSupport support) {
            return support.isDataFlavorSupported(DataFlavor.javaFileListFlavor);
        }

        @Override
        public boolean importData(TransferSupport support) {
            if (!canImport(support)) return false;
            try {
                Transferable t = support.getTransferable();
                List<File> files = (List<File>) t.getTransferData(DataFlavor.javaFileListFlavor);
                jTextFieldFilename.setText(files.get(0).getAbsolutePath());
                try {
                    insertCsv();
                } catch (CsvValidationException ex) {
                    Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                return true;
            } catch (UnsupportedFlavorException | IOException e) {
                return false;
            }
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroupPageOrientation = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldFilename = new javax.swing.JTextField();
        jButtonFile = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxDelimeter = new javax.swing.JComboBox<>();
        jTextFieldOther = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jRadioButtonTabular = new javax.swing.JRadioButton();
        jRadioButtonTabs = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jComboBoxFontName = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSpinnerFontSize = new javax.swing.JSpinner();
        jPanel7 = new javax.swing.JPanel();
        jRadioButtonVertical = new javax.swing.JRadioButton();
        jRadioButtonHorizontal = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jCheckBoxCentered = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jCheckBoxThr = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jButtonConvert = new javax.swing.JButton();
        jButtonSelectAll = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2147483647, 510));
        setMinimumSize(new java.awt.Dimension(560, 510));
        setPreferredSize(new java.awt.Dimension(560, 510));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Import"));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jTextFieldFilename.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jTextFieldFilename, gridBagConstraints);

        jButtonFile.setText("...");
        jButtonFile.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        jButtonFile.setMaximumSize(new java.awt.Dimension(23, 24));
        jButtonFile.setMinimumSize(new java.awt.Dimension(23, 24));
        jButtonFile.setPreferredSize(new java.awt.Dimension(23, 24));
        jButtonFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFileActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jButtonFile, gridBagConstraints);

        jLabel2.setIcon(UIManager.getIcon("FileView.directoryIcon"));
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Filename:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel3.add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Delimeter:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(jLabel1, gridBagConstraints);

        jComboBoxDelimeter.setMinimumSize(new java.awt.Dimension(112, 22));
        jComboBoxDelimeter.setPreferredSize(new java.awt.Dimension(112, 22));
        jComboBoxDelimeter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDelimeterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(jComboBoxDelimeter, gridBagConstraints);

        jTextFieldOther.setMinimumSize(new java.awt.Dimension(70, 22));
        jTextFieldOther.setPreferredSize(new java.awt.Dimension(70, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(jTextFieldOther, gridBagConstraints);

        jLabel4.setText("Other:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(jLabel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        jPanel3.add(jPanel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        getContentPane().add(jPanel3, gridBagConstraints);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Layout Options"));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("PDF Layout"));
        jPanel4.setToolTipText("");
        jPanel4.setMinimumSize(new java.awt.Dimension(122, 86));
        jPanel4.setPreferredSize(new java.awt.Dimension(122, 86));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        buttonGroup1.add(jRadioButtonTabular);
        jRadioButtonTabular.setText("Tabular");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel4.add(jRadioButtonTabular, gridBagConstraints);

        buttonGroup1.add(jRadioButtonTabs);
        jRadioButtonTabs.setSelected(true);
        jRadioButtonTabs.setText("Tabs");
        jRadioButtonTabs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTabsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel4.add(jRadioButtonTabs, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(jPanel4, gridBagConstraints);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Font"));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jComboBoxFontName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxFontName.setMinimumSize(new java.awt.Dimension(112, 22));
        jComboBoxFontName.setPreferredSize(new java.awt.Dimension(112, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel6.add(jComboBoxFontName, gridBagConstraints);

        jLabel5.setText("Font name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        jPanel6.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Font size:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel6.add(jLabel6, gridBagConstraints);

        jSpinnerFontSize.setModel(new javax.swing.SpinnerNumberModel(11, 8, 72, 1));
        jSpinnerFontSize.setMinimumSize(new java.awt.Dimension(112, 22));
        jSpinnerFontSize.setPreferredSize(new java.awt.Dimension(112, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel6.add(jSpinnerFontSize, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(jPanel6, gridBagConstraints);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Page orientation"));
        jPanel7.setMinimumSize(new java.awt.Dimension(122, 44));
        jPanel7.setPreferredSize(new java.awt.Dimension(122, 44));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        buttonGroupPageOrientation.add(jRadioButtonVertical);
        jRadioButtonVertical.setSelected(true);
        jRadioButtonVertical.setText("Vertical");
        jRadioButtonVertical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonVerticalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel7.add(jRadioButtonVertical, gridBagConstraints);

        buttonGroupPageOrientation.add(jRadioButtonHorizontal);
        jRadioButtonHorizontal.setText("Horizontal");
        jRadioButtonHorizontal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHorizontalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel7.add(jRadioButtonHorizontal, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(jPanel7, gridBagConstraints);

        jPanel8.setLayout(new java.awt.GridBagLayout());

        jLabel7.setText("Centered");
        jPanel8.add(jLabel7, new java.awt.GridBagConstraints());
        jPanel8.add(jCheckBoxCentered, new java.awt.GridBagConstraints());

        jLabel8.setText("Table header repeating");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel8.add(jLabel8, gridBagConstraints);
        jPanel8.add(jCheckBoxThr, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 13, 10, 13);
        jPanel5.add(jPanel8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        getContentPane().add(jPanel5, gridBagConstraints);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("CSV Preview"));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        jPanel10.setLayout(new java.awt.CardLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Select CSV to see preview");
        jLabel9.setFocusable(false);
        jPanel10.add(jLabel9, "card1");

        jScrollPane1.setMinimumSize(new java.awt.Dimension(452, 150));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 150));

        jTable1.setModel(tableModel);
        jScrollPane1.setViewportView(jTable1);

        jPanel10.add(jScrollPane1, "card2");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel9.add(jPanel10, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        getContentPane().add(jPanel9, gridBagConstraints);

        jPanel11.setLayout(new java.awt.GridBagLayout());

        jButtonConvert.setText("Convert");
        jButtonConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        jPanel11.add(jButtonConvert, gridBagConstraints);

        jButtonSelectAll.setText("Select all");
        jButtonSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectAllActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        jPanel11.add(jButtonSelectAll, gridBagConstraints);

        jButtonPrint.setText("Print");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel11.add(jButtonPrint, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        getContentPane().add(jPanel11, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFileActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV-Dateien (*.csv)", "csv");
        fileChooser.setFileFilter(filter);
        
        int response = fileChooser.showOpenDialog(null);
        
        if(response == JFileChooser.APPROVE_OPTION) {
            path = fileChooser.getSelectedFile().getAbsolutePath();
            jTextFieldFilename.setText(path);
            try {  
                insertCsv();
            } catch (IOException | CsvValidationException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonFileActionPerformed

    private void jButtonConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertActionPerformed

        
        JFileChooser fileChooser = new JFileChooser();
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("PDF-Dateien (*.pdf)", "pdf");
        fileChooser.setFileFilter(filter);
        fileChooser.setAcceptAllFileFilterUsed(false);

        int result = fileChooser.showSaveDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String filePath = selectedFile.getAbsolutePath();

            
            if (!filePath.toLowerCase().endsWith(".pdf")) {
                selectedFile = new File(filePath + ".pdf");
            }

            System.out.println("PDF wird gespeichert unter: " + selectedFile.getAbsolutePath());
            config.pdfOutputPath = Paths.get(selectedFile.getAbsolutePath());
            
        }

        ComboItem item = (ComboItem) jComboBoxDelimeter.getSelectedItem();
        config.delimiter = jTextFieldOther.getText().isBlank() ? item.getDelimiter() : jTextFieldOther.getText();
        
        config.layout = jRadioButtonTabs.isSelected() ? "tabs" : "tabular";

        config.fontName = jComboBoxFontName.getSelectedItem().toString();
        config.fontSize = (int) jSpinnerFontSize.getValue();

        config.isLandscape = jRadioButtonHorizontal.isSelected();
        config.isCentered = jCheckBoxCentered.isSelected();
        config.thr = jCheckBoxThr.isSelected();
        
        List<Integer> selectedRows = new ArrayList<>();
        for(int row = 0; row < jTable1.getRowCount(); row++) {
            boolean isSelected = (boolean) jTable1.getValueAt(row, 0);
            if(isSelected) {
                selectedRows.add(row);
            }
        }
        
        config.selectedRows = selectedRows;

        try {
            if(config.csvPath != null) {
                service.convert(config, data);  
                JOptionPane.showMessageDialog(this, "PDF successfully created.");
            } else {
                JOptionPane.showMessageDialog(this, "Pfad nicht gefunden.");
            }
        } catch (CsvValidationException | IOException e) {}
    }//GEN-LAST:event_jButtonConvertActionPerformed

    private void loadConfig() {
        service = new CSV2PDF();

        // Beispiel-Konfiguration
        config = new CSV2PDF.PDFConfig();
        config.csvPath = Paths.get(jTextFieldFilename.getText()); // Ersetze durch deinen CSV-Pfad

        // Delimeter
        ComboItem item = (ComboItem) jComboBoxDelimeter.getSelectedItem();
        config.delimiter = jTextFieldOther.getText().isBlank() ? item.getDelimiter() : jTextFieldOther.getText();
    }
    
    private void insertCsv() throws IOException, CsvValidationException {
        loadConfig();
        data = service.loadCSV(config);
        
        tableModel = new DefaultTableModel() {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return columnIndex == 0 ? Boolean.class : String.class;
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 0; // Only checkbox editable
            }
        };
        jTable1.setModel(tableModel);

        String[] headers = data.get(0);
        String[] headersWithCheckbox = new String[headers.length + 1];
        headersWithCheckbox[0] = "Select";
        System.arraycopy(headers, 0, headersWithCheckbox, 1, headers.length);
        tableModel.setColumnIdentifiers(headersWithCheckbox);

        for (int i = 1; i < data.size(); i++) {
            String[] row = data.get(i);
            Object[] newRow = new Object[row.length + 1];
            newRow[0] = true; // Default: checkbox selected
            System.arraycopy(row, 0, newRow, 1, row.length);
            tableModel.addRow(newRow);
        }

        CardLayout layout = (CardLayout) jPanel10.getLayout();
        layout.show(jPanel10, "card2");
    }
    
    private void jRadioButtonTabsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTabsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonTabsActionPerformed

    private void jComboBoxDelimeterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDelimeterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDelimeterActionPerformed

    private void jRadioButtonVerticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonVerticalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonVerticalActionPerformed

    private void jRadioButtonHorizontalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHorizontalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonHorizontalActionPerformed

    private void jButtonSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectAllActionPerformed
        for(int row = 0; row < jTable1.getRowCount(); row++) {
            boolean isSelected = (boolean) jTable1.getValueAt(row, 0);
            jTable1.setValueAt(!isSelected, row, 0);
        }
    }//GEN-LAST:event_jButtonSelectAllActionPerformed

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
        config.pdfOutputPath = Paths.get("C:/Users/Cem/Desktop/test.pdf");
        
        ComboItem item = (ComboItem) jComboBoxDelimeter.getSelectedItem();
        config.delimiter = jTextFieldOther.getText().isBlank() ? item.getDelimiter() : jTextFieldOther.getText();       
        
        config.fontName = jComboBoxFontName.getSelectedItem().toString();
        config.fontSize = (int) jSpinnerFontSize.getValue();

        config.isLandscape = jRadioButtonHorizontal.isSelected();
        config.isCentered = jCheckBoxCentered.isSelected();
        config.thr = jCheckBoxThr.isSelected();
        
        List<Integer> selectedRows = new ArrayList<>();
        for(int row = 0; row < jTable1.getRowCount(); row++) {
            boolean isSelected = (boolean) jTable1.getValueAt(row, 0);
            if(isSelected) {
                selectedRows.add(row);
            }
        }
        
        config.selectedRows = selectedRows;

        try {
            if(config.csvPath != null) {
                service.convert(config, data);  
                
            }
        } catch (CsvValidationException | IOException e) {}
        
        try {
            service.printPDF(config.pdfOutputPath);
        } catch (IOException | PrinterException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroupPageOrientation;
    private javax.swing.JButton jButtonConvert;
    private javax.swing.JButton jButtonFile;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonSelectAll;
    private javax.swing.JCheckBox jCheckBoxCentered;
    private javax.swing.JCheckBox jCheckBoxThr;
    private javax.swing.JComboBox<ComboItem> jComboBoxDelimeter;
    private javax.swing.JComboBox<String> jComboBoxFontName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButtonHorizontal;
    private javax.swing.JRadioButton jRadioButtonTabs;
    private javax.swing.JRadioButton jRadioButtonTabular;
    private javax.swing.JRadioButton jRadioButtonVertical;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerFontSize;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldFilename;
    private javax.swing.JTextField jTextFieldOther;
    // End of variables declaration//GEN-END:variables
}
